name = "sbe-assistant-pwa"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB" # Hãy đổi thành sbe_memory_db nếu code của bạn dùng env.sbe_memory_db
database_name = "sbe-memory-db"
database_id = "87e77f75-64f7-49c4-a3e1-e823c56a23f0"